export const ErrorCodes = {
  UNAUTHORIZED: "UNAUTHORIZED",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  EMAIL_EXISTS: "EMAIL_EXISTS",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  BOOKING_NOT_FOUND: "BOOKING_NOT_FOUND",
  INVALID_STATUS_TRANSITION: "INVALID_STATUS_TRANSITION",
  CANNOT_BOOK_OWN_SERVICE: "CANNOT_BOOK_OWN_SERVICE",
  REVIEW_ALREADY_EXISTS: "REVIEW_ALREADY_EXISTS",
  REVIEW_EDIT_WINDOW_CLOSED: "REVIEW_EDIT_WINDOW_CLOSED",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  STRIPE_ERROR: "STRIPE_ERROR",
  UPLOAD_FAILED: "UPLOAD_FAILED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
